### ISSUE TITLE
Unneeded use of Test::Requires

### ISSUE THREAD

**Issue by ppisar** [RsrchBoy/moosex-attributeshortcuts#19]
0.033 added t/others/semiaffordanceaccessor.t that probes MooseX::SemiAffordanceAccessor with Test::Requires. That looks like tests could pass without having MooseX::SemiAffordanceAccessor installed. But that's not true because t/00-check-deps.t fails without MooseX::SemiAffordanceAccessor.

Either you should weaken dependency on MooseX::SemiAffordanceAccessor dependency to recommend level, or you shouldn't use Test::Requires at all and remove that from dependency list.

**Comment by RsrchBoy** [comment]
Thanks!  Fixed in 0.034.
